Aether.registerFeature({id:'infrastructure',label:'Infrastructure Integrations',icon:'network',description:'Connect private infrastructure through your outbound gateway. Credentials stay in your network; requests are read-only.',mount({root,notify,escapeHtml:e}){
 const admin=window.AETHER_USER?.role==='admin';let data;
 const field=(id,label,extra='')=>`<label for="${id}" class="text-xs font-semibold">${label}</label><input id="${id}" class="detail-input" required ${extra}>`;
 const call=(path,method='POST',body={})=>AppAuth.api(path,{method,body:JSON.stringify(body)});
 async function load(){try{data=await AppAuth.api('/api/infrastructure');render()}catch(err){root.textContent=err.message}}
 function render(){
  const active=data.gateways.filter(g=>g.active);
  root.innerHTML=`<section class="bg-blue-50 border border-blue-200 rounded-xl p-5 mb-6"><h2 class="font-bold text-sm">Private network connection</h2><p class="text-xs mt-2">Run the gateway on a machine that can reach your infrastructure. It polls this platform over outbound HTTPS. No inbound network access is required. Product credentials are read from environment variables on that machine.</p><p class="text-xs mt-2">REST adapters: NetApp ONTAP, VMware vCenter, ServiceNow, Kubernetes and Dynatrace Classic. Other products require a configured REST path or a local adapter. Autonomous remediation is not enabled.</p><a class="text-blue-700 text-xs underline mt-2 inline-block" href="/gateway-setup" target="_blank">Gateway installation and adapter guide</a></section><div class="grid grid-cols-1 xl:grid-cols-3 gap-6"><section class="bg-white border rounded-xl p-5"><h2 class="font-bold text-sm mb-3">Network gateways</h2>${active.length?active.map(g=>`<div class="border-b py-3"><b class="text-xs">${e(g.name)}</b><p class="text-xs text-slate-500">${g.last_seen?'Last heartbeat: '+e(new Date(g.last_seen).toLocaleString()):'Awaiting first gateway heartbeat'}</p>${admin?`<button class="text-xs text-rose-700 mt-1" data-revoke="${g.id}">Revoke access</button>`:''}</div>`).join(''):'<p class="text-xs text-slate-500">No gateways registered.</p>'}${admin?'<button id="pairGateway" class="detail-button mt-4">Register gateway</button>':''}</section><section class="xl:col-span-2 bg-white border rounded-xl p-5"><div class="flex justify-between"><h2 class="font-bold text-sm">Infrastructure connections</h2>${admin?'<button id="addInfra" class="detail-button">Add connection</button>':''}</div><div class="mt-4">${data.connections.length?data.connections.map(c=>{
   const j=data.jobs.find(j=>j.connection_id===c.id),pending=j&&['queued','running'].includes(j.status)&&Date.now()-j.created_at<120000;
   return `<article class="border rounded-lg p-4 mb-3"><div class="flex justify-between"><b class="text-sm">${e(c.name)}</b><span class="text-xs ${c.status==='Connected'?'text-emerald-700':'text-slate-600'}">${pending?'Request '+e(j.status):j&&['queued','running','expired'].includes(j.status)?'Request timed out · gateway unavailable':e(c.status)}</span></div><p class="text-xs text-slate-500 mt-1">${e(data.products.find(p=>p.id===c.product)?.name)} · Profile ${e(c.credential_ref)}</p><p class="text-xs mt-2">${e(c.message||'No live request has completed.')}</p>${c.checked_at?`<p class="text-xs text-slate-500">Last checked: ${e(new Date(c.checked_at).toLocaleString())}</p>`:''}<div class="flex gap-3 mt-3">${admin?`<button data-action="test" data-id="${c.id}" class="text-xs text-blue-700" ${pending?'disabled':''}>Test connection</button><button data-action="inventory" data-id="${c.id}" class="text-xs text-blue-700" ${pending?'disabled':''}>Sync inventory</button>`:''}<button data-detail="${c.id}" class="text-xs text-blue-700">View inventory (${c.inventory.length})</button>${admin?`<button data-action="delete" data-id="${c.id}" class="text-xs text-rose-700">Remove</button>`:''}</div></article>`
  }).join(''):'<p class="text-xs text-slate-500">Add a product connection to discover real infrastructure. No sample inventory is displayed here.</p>'}</div></section></div><section class="bg-white border rounded-xl p-5 mt-6"><h2 class="font-bold text-sm mb-3">Product catalog</h2><div class="grid grid-cols-2 md:grid-cols-4 gap-3">${data.products.map(p=>`<div class="bg-slate-50 border rounded-lg p-3"><b class="text-xs">${e(p.name)}</b><p class="text-xs text-slate-500 mt-1">${e(p.adapter==='REST'?'Read-only REST adapter':'Configure REST / local adapter')}</p></div>`).join('')}</div></section>`;
  if(admin){root.querySelector('#pairGateway').onclick=()=>{detail('Register private network gateway',`<form id="gatewayForm">${field('gatewayName','Gateway name','maxlength="80" placeholder="e.g. Corporate IT gateway"')}<button class="detail-button">Create gateway credential</button><p id="gatewayError" role="alert"></p></form>`);document.getElementById('gatewayForm').onsubmit=async ev=>{ev.preventDefault();try{const g=await call('/api/infrastructure/gateways','POST',{name:document.getElementById('gatewayName').value});detail('Gateway credential · shown once',`<p>Copy this token into AETHER_GATEWAY_TOKEN on your gateway machine. Treat it as a password.</p><textarea class="detail-input" readonly aria-label="Gateway token">${e(g.token)}</textarea><p>Download the gateway package from the installation guide. This credential can only poll read-only requests and return results for its own connections.</p><a href="/gateway-setup" target="_blank" class="text-blue-700 underline">Open setup guide</a>`);await load()}catch(err){document.getElementById('gatewayError').textContent=err.message}}};
  root.querySelector('#addInfra').onclick=()=>{if(!active.length){notify('Register a gateway first.','info');return}detail('Add infrastructure connection',`<form id="infraForm">${field('infraName','Connection name','maxlength="80"')}<label for="infraProduct">Product</label><select id="infraProduct" class="detail-input">${data.products.map(p=>`<option value="${p.id}">${e(p.name)}</option>`).join('')}</select><label for="infraGateway">Gateway</label><select id="infraGateway" class="detail-input">${active.map(g=>`<option value="${g.id}">${e(g.name)}</option>`).join('')}</select>${field('infraRef','Local configuration alias','pattern="[a-zA-Z0-9_-]{1,64}" placeholder="e.g. netapp_prod"')}<p class="text-xs">The alias must match a profile in the gateway configuration. Store endpoint URLs and credentials on the gateway machine.</p><p id="infraError" role="alert"></p><button class="detail-button mt-3">Save connection</button></form>`);document.getElementById('infraForm').onsubmit=async ev=>{ev.preventDefault();try{await call('/api/infrastructure/connections','POST',{name:document.getElementById('infraName').value,product:document.getElementById('infraProduct').value,gatewayId:document.getElementById('infraGateway').value,credentialRef:document.getElementById('infraRef').value});closeDetail();await load()}catch(err){document.getElementById('infraError').textContent=err.message}}};
  root.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await call('/api/infrastructure/connections/'+b.dataset.id+(b.dataset.action==='delete'?'':'/'+b.dataset.action),b.dataset.action==='delete'?'DELETE':'POST');await load()}catch(err){notify(err.message,'danger');b.disabled=false}});
  root.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{try{await call('/api/infrastructure/gateways/'+b.dataset.revoke,'DELETE');await load()}catch(err){notify(err.message,'danger')}});
  }
  root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const c=data.connections.find(c=>c.id===b.dataset.detail);detail('Live inventory · '+c.name,c.inventory.length?`<table class="w-full text-xs text-left"><thead><tr><th>Name</th><th>Type</th><th>Status</th></tr></thead><tbody>${c.inventory.map(r=>`<tr class="border-t"><td class="p-3">${e(r.name)}</td><td>${e(r.type)}</td><td>${e(r.status)}</td></tr>`).join('')}</tbody></table><p class="text-xs mt-3">Latest successful snapshot · up to 50 resources. Checked ${e(c.checked_at||'')}.</p>`:'<p>No resources have been synchronized. Run Sync inventory after the gateway is connected.</p>')});
 }
 load();setInterval(()=>{if(document.getElementById('view-infrastructure')&&!document.getElementById('view-infrastructure').classList.contains('hidden'))load()},7000);
}});
