Aether.registerFeature({id:'python-agents',label:'Python Agents',icon:'bot',description:'Onboard your existing Python agents, run them through a private gateway and inspect their results.',mount({root,notify,escapeHtml:e}){
 const admin=window.AETHER_USER?.role==='admin';let data,gatewayData;
 const api=(path,method='POST',body={})=>AppAuth.api(path,{method,body:JSON.stringify(body)});
 const input=(id,label,attrs='')=>`<label for="${id}" class="text-xs font-semibold">${label}</label><input id="${id}" class="detail-input" required ${attrs}>`;
 const date=v=>new Date(v).toLocaleString();
 async function load(){try{[gatewayData,data]=await Promise.all([AppAuth.api('/api/infrastructure'),AppAuth.api('/api/python-agents')]);render()}catch(err){root.textContent=err.message}}
 function render(){
  root.innerHTML=`<section class="bg-blue-50 border border-blue-200 rounded-xl p-5 mb-6"><h2 class="text-sm font-bold">Bring your existing agents</h2><p class="text-xs mt-2">Keep Python code, virtual environments and credentials inside your network. Register a locally configured agent alias here. The gateway runs its approved command with JSON input and returns the JSON result.</p><a href="/python-agent-setup" target="_blank" class="text-xs text-blue-700 underline inline-block mt-3">Python agent onboarding guide and example files</a></section><section class="bg-white border rounded-xl p-5"><div class="flex justify-between items-center"><h2 class="text-sm font-bold">Registered Python agents</h2>${admin?'<button id="onboardPython" class="detail-button">Onboard Python agent</button>':''}</div><div class="mt-4">${data.agents.length?data.agents.map(a=>{const gw=gatewayData.gateways.find(g=>g.id===a.gateway_id);const running=data.runs.some(r=>r.agent_id===a.id&&['queued','running'].includes(r.status));return `<article class="border rounded-xl p-4 mb-3"><div class="flex justify-between"><h3 class="text-sm font-bold">${e(a.name)}</h3><span class="text-xs text-slate-500">${a.enabled?'Enabled':'Disabled'}</span></div><p class="text-xs mt-2">${e(a.description)}</p><p class="text-xs text-slate-500 mt-2">Gateway: ${e(gw?.name||'Unavailable')} · Alias: ${e(a.agent_ref)} · ${a.mode==='change'?'Changes allowed with per-run approval':'Observation mode'}</p><p class="text-xs mt-1">${gw?.active?(gw.last_seen?'Gateway last seen '+e(date(gw.last_seen)):'Waiting for gateway heartbeat'):'Gateway access revoked'}</p><div class="flex gap-3 mt-3">${admin?`<button class="text-xs text-blue-700" data-run-agent="${a.id}" ${!a.enabled||!gw?.active||running?'disabled':''}>${running?'Run pending':'Run agent'}</button><button class="text-xs text-slate-600" data-toggle-agent="${a.id}">${a.enabled?'Disable':'Enable'}</button>`:''}<button class="text-xs text-blue-700" data-agent-info="${a.id}">Details</button></div></article>`}).join(''):'<p class="text-xs text-slate-500">No Python agents onboarded. Add an existing script or callable using a local gateway alias.</p>'}</div></section><section class="bg-white border rounded-xl p-5 mt-6"><h2 class="text-sm font-bold mb-4">Run history</h2>${data.runs.length?`<div class="overflow-auto"><table class="w-full text-xs text-left"><thead><tr><th>Agent</th><th>Status</th><th>Requested by</th><th>Started</th><th>Result</th></tr></thead><tbody>${data.runs.map(r=>`<tr class="border-t"><td class="p-3">${e(data.agents.find(a=>a.id===r.agent_id)?.name||r.agent_id)}</td><td>${e(r.status)}</td><td>${e(r.requested_by)}</td><td>${e(date(r.created_at))}</td><td><button data-run-detail="${r.id}" class="text-blue-700">Inspect run</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="text-xs text-slate-500">Run an agent to see its status, input and returned output here.</p>'}</section>`;
  if(admin){
   root.querySelector('#onboardPython').onclick=()=>{const gateways=gatewayData.gateways.filter(g=>g.active);if(!gateways.length){notify('Register a private-network gateway in Infrastructure Integrations first.','info');Aether.navigate('infrastructure');return}detail('Onboard existing Python agent',`<form id="onboardPythonForm">${input('pythonName','Agent name','maxlength="80"')}<label for="pythonDescription">Description</label><textarea id="pythonDescription" class="detail-input" maxlength="1000"></textarea><label for="pythonGateway">Private-network gateway</label><select id="pythonGateway" class="detail-input">${gateways.map(g=>`<option value="${g.id}">${e(g.name)}</option>`).join('')}</select>${input('pythonAlias','Local agent alias','pattern="[a-zA-Z0-9_-]{1,64}" placeholder="my_python_agent"')}<label for="pythonMode">Execution mode</label><select id="pythonMode" class="detail-input"><option value="observe">Observation</option><option value="change">May change infrastructure · approval per run</option></select><p class="text-xs mt-2">The alias must match an agents entry in your gateway configuration. Registering does not upload or execute your code. Install dependencies and use the appropriate service-account permissions on the gateway.</p><p id="pythonFormError" role="alert"></p><button class="detail-button mt-3">Onboard agent</button></form>`);document.getElementById('onboardPythonForm').onsubmit=async ev=>{ev.preventDefault();const submit=ev.target.querySelector('button');submit.disabled=true;try{await api('/api/python-agents','POST',{name:document.getElementById('pythonName').value,description:document.getElementById('pythonDescription').value,gatewayId:document.getElementById('pythonGateway').value,agentRef:document.getElementById('pythonAlias').value,mode:document.getElementById('pythonMode').value});closeDetail();await load();notify('Python agent registered.','success')}catch(err){document.getElementById('pythonFormError').textContent=err.message;submit.disabled=false}}};
   root.querySelectorAll('[data-toggle-agent]').forEach(b=>b.onclick=async()=>{const a=data.agents.find(a=>a.id===b.dataset.toggleAgent);try{await api('/api/python-agents/'+a.id,'PATCH',{enabled:!a.enabled});await load()}catch(err){notify(err.message,'danger')}});
   root.querySelectorAll('[data-run-agent]').forEach(b=>b.onclick=()=>{const a=data.agents.find(a=>a.id===b.dataset.runAgent);detail('Run Python agent · '+a.name,`<form id="pythonRunForm"><label for="pythonRunInput">Input (JSON object)</label><textarea id="pythonRunInput" class="detail-input font-mono" rows="7" maxlength="16000" required>{"task":"inspect infrastructure"}</textarea><p class="text-xs">Inputs and returned results are stored in this workspace and visible to its users. Keep credentials in the gateway environment.</p>${a.mode==='change'?'<label class="block text-sm mt-3"><input id="pythonApprove" type="checkbox" required> I approve this agent run, including its potential infrastructure changes.</label>':''}<p id="pythonRunError" role="alert"></p><button class="detail-button mt-3">${a.mode==='change'?'Approve and run':'Run agent'}</button></form>`);document.getElementById('pythonRunForm').onsubmit=async ev=>{ev.preventDefault();const submit=ev.target.querySelector('button');submit.disabled=true;try{const value=JSON.parse(document.getElementById('pythonRunInput').value);const r=await api('/api/python-agents/'+a.id+'/run','POST',{input:value,approved:document.getElementById('pythonApprove')?.checked||false});closeDetail();await load();notify('Run queued for your gateway.','success');await inspectRun(r.id)}catch(err){document.getElementById('pythonRunError').textContent=err instanceof SyntaxError?'Enter valid JSON input.':err.message;submit.disabled=false}}});
  }
  root.querySelectorAll('[data-agent-info]').forEach(b=>b.onclick=()=>{const a=data.agents.find(a=>a.id===b.dataset.agentInfo);detail('Python agent · '+a.name,`<p>${e(a.description)}</p><pre class="text-xs bg-slate-50 p-3 rounded mt-3 overflow-auto">${e(JSON.stringify({agents:{[a.agent_ref]:{mode:a.mode,...(a.mode==='change'?{allowChanges:true}:{}),command:['/path/to/venv/bin/python','/path/to/agent_adapter.py']}}},null,2))}</pre><p class="text-xs mt-3">Merge this agents entry into your local gateway configuration. Your adapter reads a JSON object from stdin and writes one JSON value to stdout. Use the onboarding guide to wrap an existing Python function.</p><a href="/python-agent-setup" target="_blank" class="text-blue-700 underline">Open onboarding guide</a>`)});
  root.querySelectorAll('[data-run-detail]').forEach(b=>b.onclick=()=>inspectRun(b.dataset.runDetail));
 }
 async function inspectRun(id){try{const {run}=await AppAuth.api('/api/python-agents/runs/'+id);detail('Python run · '+run.status,`<p class="text-xs">Run ID: ${e(run.id)} · Requested by ${e(run.requested_by)}</p><p class="text-xs mt-2">${e(run.error||(['queued','running'].includes(run.status)?'Waiting for gateway completion. Use Refresh run to check for results.':'Completed.'))}</p><h3 class="font-bold text-sm mt-4">Input</h3><pre class="text-xs bg-slate-50 p-3 overflow-auto">${e(JSON.stringify(run.input,null,2))}</pre><h3 class="font-bold text-sm mt-4">Output</h3><pre class="text-xs bg-slate-50 p-3 overflow-auto">${e(run.output===null?'No output returned.':JSON.stringify(run.output,null,2))}</pre><button id="refreshPythonRun" class="detail-button mt-3">Refresh run</button>`);document.getElementById('refreshPythonRun').onclick=()=>inspectRun(id)}catch(err){notify(err.message,'danger')}}
 load();setInterval(()=>{if(document.getElementById('view-python-agents')&&!document.getElementById('view-python-agents').classList.contains('hidden'))load()},5000);
}});
