import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import worker from '../dist/server/index.js';
const sqlite=new DatabaseSync(':memory:');
const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this},async run(){return sqlite.prepare(sql).run(...args)},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}}}}};
const env={BOOTSTRAP_ADMIN_USERNAME:'itops',BOOTSTRAP_ADMIN_PASSWORD:'itops-test-password',DB,ASSETS:{fetch:async req=>new Response(new URL(req.url).pathname.includes('login')?'login screen':'<html><head></head><body>application</body></html>',{headers:{'Content-Type':'text/html'}})}};
const origin='https://app.example';
const call=(path,method='GET',data,cookie)=>worker.fetch(new Request(origin+path,{method,headers:{Origin:origin,...(data?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(data?{body:JSON.stringify(data)}:{})}),env);
const login=await call('/api/auth/login','POST',{username:'itops',password:'itops-test-password'});assert.equal(login.status,200);
const setCookie=login.headers.get('Set-Cookie');assert.match(setCookie,/^__Host-aether_session=/);assert.match(setCookie,/Secure/);assert.match(setCookie,/HttpOnly/);const cookie=setCookie.split(';')[0];
const row=sqlite.prepare("SELECT * FROM app_users WHERE username='itops'").get();assert.notEqual(row.password_hash,'itops');assert.equal(row.password_hash.length,64);assert.equal(row.salt.length,32);
console.log('PASS HTTPS-only session cookie and salted password hash');
const created=await call('/api/users','POST',{username:'backend-test',password:'testpass-long-password'},cookie);assert.equal(created.status,201);const user=await created.json();assert.equal(user.user.password_hash,undefined);
const missingOrigin=await worker.fetch(new Request(origin+'/api/users',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:'{}'}),env);assert.equal(missingOrigin.status,403);
const token=cookie.split('=')[1];const session=sqlite.prepare('SELECT * FROM app_sessions').get();assert.notEqual(session.token_hash,token);
console.log('PASS Session tokens hashed at rest and writes require matching Origin');
sqlite.prepare('UPDATE app_sessions SET expires_at=0').run();assert.equal((await call('/api/auth/me','GET',null,cookie)).status,401);
console.log('PASS Expired sessions cannot authenticate');
for(let n=0;n<10;n++)assert.equal((await call('/api/auth/login','POST',{username:'unknown-user',password:'incorrect'})).status,401);
assert.equal((await call('/api/auth/login','POST',{username:'itops',password:'itops-test-password'})).status,429);
console.log('PASS Repeated failed sign-ins are rate limited');
sqlite.close();console.log('4 authentication API checks passed.');
