import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {writeFileSync,unlinkSync} from 'node:fs';
const base='http://127.0.0.1:3004';const browser=await chromium.launch({executablePath:'/home/lekha/.agent-browser/browsers/chrome-154.0.8037.92/chrome',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let gw,agent,process;
try{
 await page.goto(base+'/#observability');await page.locator('#loginUser').fill('itops');await page.locator('#loginPassword').fill('itops');await page.locator('#loginSubmit').click();await page.locator('#view-observability #refreshLiveData').waitFor();
 assert.equal(await page.locator('#view-observability').isVisible(),true);assert.equal(await page.locator('.sim-banner').count(),0);assert.equal(await page.locator('[data-tab="observability"]').count(),1);assert.equal(await page.locator('[data-tab="observability"]').count(),1);
 await page.locator('[data-tab="observability"]').click();await page.locator('#view-observability #refreshLiveData').waitFor();assert.match(await page.locator('#view-observability').innerText(),/Not reported/);assert.ok(!await page.locator('#view-observability').innerText().then(x=>x.includes('78.4%')));
 gw=await page.evaluate(()=>AppAuth.api('/api/infrastructure/gateways',{method:'POST',body:JSON.stringify({name:'Live metrics gateway'})}));agent=await page.evaluate(id=>AppAuth.api('/api/python-agents',{method:'POST',body:JSON.stringify({name:'Measured Python agent',description:'Actual execution test',gatewayId:id,agentRef:'measured',mode:'observe'})}),gw.id);
 writeFileSync('/tmp/aether-live-flow.json',JSON.stringify({site:base,profiles:{},agents:{measured:{mode:'observe',command:['python3','gateway/python_entrypoint.py','--module','example_agent']}}}));
 process=spawn('python3',['gateway/agent.py','--config','/tmp/aether-live-flow.json'],{env:{...globalThis.process.env,AETHER_GATEWAY_TOKEN:gw.token,AETHER_GATEWAY_ALLOW_LOCAL_HTTP:'1'},stdio:'ignore'});
 const run=await page.evaluate(id=>AppAuth.api('/api/python-agents/'+id+'/run',{method:'POST',body:JSON.stringify({input:{task:'actual metrics'}})}),agent.id);
 await page.locator('[data-tab="observability"]').click();await page.getByRole('row').filter({hasText:'Measured Python agent'}).getByRole('cell',{name:'succeeded',exact:true}).waitFor({timeout:30000});
 let telemetry=await page.evaluate(()=>AppAuth.api('/api/telemetry'));const measured=telemetry.runs.find(r=>r.id===run.id);assert.ok(measured.duration_ms>=0);assert.equal(measured.input_tokens,null);assert.equal(measured.duration_source,'gateway');
 await page.locator('[data-actual-run="'+run.id+'"]').click();await page.getByText('Existing Python callable executed successfully.',{exact:false}).waitFor();await page.getByRole('button',{name:'Close details',exact:true}).click();
 const child=spawn('python3',['gateway/report_execution.py','--site',base,'--agent','measured','--execution-id','existing-ui-1'],{env:{...globalThis.process.env,AETHER_GATEWAY_TOKEN:gw.token,AETHER_GATEWAY_ALLOW_LOCAL_HTTP:'1'},stdio:['pipe','ignore','inherit']});child.stdin.end(JSON.stringify({ok:true,input:{task:'external UI'},output:{summary:'Existing UI reported result'},durationMs:1000,usage:{inputTokens:100,outputTokens:20,cost:0.012,currency:'USD',provider:'test-provider',model:'reported-test-model'}}));await new Promise((resolve,reject)=>child.on('exit',code=>code===0?resolve():reject(Error('Reporter failed'))));
 await page.locator('[data-tab="observability"]').click();await page.getByText('reported-test-model',{exact:true}).first().waitFor({timeout:15000});await page.locator('#view-observability #refreshLiveData').click();telemetry=await page.evaluate(()=>AppAuth.api('/api/telemetry'));assert.equal(telemetry.aggregate.totalTokens,120);assert.equal(telemetry.costs[0].amount,0.012);
 await page.screenshot({path:'test-results/live-tokenomics.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
 console.log('PASS truthful live dashboard/tokenomics, no sample numbers, actual Python execution duration, result drill-down, external UI reporting helper, reported tokens/cost, mobile layout and no page errors');
}finally{
 if(process)process.kill();if(agent)await page.request.patch(base+'/api/python-agents/'+agent.id,{headers:{Origin:base},data:{enabled:false}});if(gw)await page.request.delete(base+'/api/infrastructure/gateways/'+gw.id,{headers:{Origin:base},data:{}});try{unlinkSync('/tmp/aether-live-flow.json')}catch{}await browser.close();
}
