import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import worker from '../dist/server/index.js';
const sqlite=new DatabaseSync(':memory:');
const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this},async run(){return sqlite.prepare(sql).run(...args)},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}}}}};
const env={BOOTSTRAP_ADMIN_USERNAME:'itops',BOOTSTRAP_ADMIN_PASSWORD:'itops-test-password',DB,ASSETS:{fetch:async()=>new Response('missing',{status:404})}};const origin='https://python.test';
const call=(path,method='GET',data,cookie,token)=>worker.fetch(new Request(origin+path,{method,headers:{Origin:origin,...(data?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(data?{body:JSON.stringify(data)}:{})}),env);
const login=await call('/api/auth/login','POST',{username:'itops',password:'itops-test-password'});const cookie=login.headers.get('Set-Cookie').split(';')[0];
assert.equal((await call('/api/python-agents')).status,401);
const gateway=await (await call('/api/infrastructure/gateways','POST',{name:'Python gateway'},cookie)).json();
const other=await (await call('/api/infrastructure/gateways','POST',{name:'Other gateway'},cookie)).json();
const create=mode=>call('/api/python-agents','POST',{name:'Existing Python',description:'My agent',gatewayId:gateway.id,agentRef:'my_agent',mode},cookie);
const agent=await (await create('observe')).json();assert.ok(agent.id);
assert.equal((await call('/api/python-agents/'+agent.id+'/run','POST',{input:[]},cookie)).status,400);
const run=await (await call('/api/python-agents/'+agent.id+'/run','POST',{input:{task:'diagnose'}},cookie)).json();assert.ok(run.id);
assert.equal((await call('/api/python-agents/'+agent.id+'/run','POST',{input:{}},cookie)).status,409);
assert.equal((await (await call('/api/gateway/poll','POST',{},null,gateway.token)).json()).job,null);
assert.equal((await (await call('/api/gateway/poll','POST',{capabilities:['python-agents']},null,other.token)).json()).job,null);
const poll=await (await call('/api/gateway/poll','POST',{capabilities:['python-agents']},null,gateway.token)).json();assert.equal(poll.job.agentRef,'my_agent');assert.deepEqual(poll.job.input,{task:'diagnose'});assert.equal(poll.job.kind,'python-agent');assert.equal(poll.job.command,undefined);
assert.equal((await call('/api/gateway/python/result','POST',{jobId:run.id,ok:true,output:{result:'done'}},null,other.token)).status,409);
assert.equal((await call('/api/gateway/python/result','POST',{jobId:run.id,ok:true,output:{result:'done'}},null,gateway.token)).status,200);
assert.equal((await call('/api/gateway/python/result','POST',{jobId:run.id,ok:true,output:{}},null,gateway.token)).status,409);
const detail=await (await call('/api/python-agents/runs/'+run.id,'GET',null,cookie)).json();assert.equal(detail.run.status,'succeeded');assert.deepEqual(detail.run.output,{result:'done'});
const changeAgent=await (await create('change')).json();assert.equal((await call('/api/python-agents/'+changeAgent.id+'/run','POST',{input:{}},cookie)).status,403);assert.equal((await call('/api/python-agents/'+changeAgent.id+'/run','POST',{input:{},approved:true},cookie)).status,202);
await call('/api/python-agents/'+changeAgent.id,'PATCH',{enabled:false},cookie);assert.equal(sqlite.prepare('SELECT status FROM python_runs WHERE agent_id=?').get(changeAgent.id).status,'cancelled');assert.equal((await call('/api/python-agents/'+changeAgent.id+'/run','POST',{input:{},approved:true},cookie)).status,409);
const stale=await (await call('/api/python-agents/'+agent.id+'/run','POST',{input:{}},cookie)).json();sqlite.prepare('UPDATE python_runs SET created_at=0 WHERE id=?').run(stale.id);await call('/api/python-agents','GET',null,cookie);assert.equal(sqlite.prepare('SELECT status FROM python_runs WHERE id=?').get(stale.id).status,'expired');
await call('/api/users','POST',{username:'observer',password:'observer-long-password'},cookie);const op=await call('/api/auth/login','POST',{username:'observer',password:'observer-long-password'});const opCookie=op.headers.get('Set-Cookie').split(';')[0];assert.equal((await call('/api/python-agents/'+agent.id+'/run','POST',{input:{}},opCookie)).status,403);assert.equal((await call('/api/python-agents/runs/'+run.id,'GET',null,opCookie)).status,200);
await call('/api/infrastructure/gateways/'+gateway.id,'DELETE',{},cookie);assert.equal((await call('/api/python-agents/'+agent.id+'/run','POST',{input:{}},cookie)).status,409);
console.log('PASS Python agent registration, JSON validation, gateway ownership, legacy compatibility, run results, replay rejection, per-run approval, disable, expiry and role protection');sqlite.close();
