server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/member/ { proxy_pass http://member-service:3001/; }
  location /api/claims/ { proxy_pass http://claims-service:3002/; }
  location /api/providers/ { proxy_pass http://provider-service:3003/; }
  location /api/care/ { proxy_pass http://care-service:3004/; }

  location /health { return 200 '{"status":"healthy","service":"gateway"}'; add_header Content-Type application/json; }
  location / { try_files $uri $uri/ /index.html; }
}

